### ISSUE TITLE
Api freezes if character doesn't exist.

### ISSUE THREAD

**Issue by AussieEevee** [danjagnow/ArgentPonyWarcraftClient#43]
I have the following code

Character x = await client.GetCharacterAsync(realm, charactername, CharacterFields.All);
            if (x.Name == null)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Program.Log($"Error retrieving {charactername}'s information.\nThey may not be level ten yet.\nProceeding to next character...");
                Console.ForegroundColor = ConsoleColor.White;
                Stats.Levels.lowlevel += 1;
                Runtime.errorcharacters = Runtime.errorcharacters + $"Name: {charactername}; Realm: {realm}; Account: {account}\n";
                return;
            }

It works perfectly on characters that are at least level 10....

But nothing happens if the character is under level 10, or has been deleted. It just sits there. Mine sat there for over 10 minutes, when I want the api to trigger the if statement if the character doesn't exist on the armory.

Thanks.

**Comment by AussieEevee** [comment]
It's also doing this if the character has other information that is empty and I try to access it. 

For example

Program.UpdateSheet($"K{cell}", $"{x.Professions.Primary[1].Name}({x.Professions.Primary[1].Rank})", $"profession 2");

Doesn't give an error or return a null value (preferable)... it just sits there.

But if the character has professions, it works just fine.

**Comment by AussieEevee** [comment]
Okay, so I got it working by changing it to a try catch

try
            {
                x = await client.GetCharacterAsync(realm, charactername, CharacterFields.All);
            }

            catch
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Program.Log($"Error retrieving {charactername}'s information.\nThey may not be level ten yet.\nProceeding to next character...");
                Console.ForegroundColor = ConsoleColor.White;
                Stats.Levels.lowlevel += 1;
                Runtime.errorcharacters = Runtime.errorcharacters + $"Name: {charactername}; Realm: {realm}; Account: {account}\n";
                return;
            }

**Comment by TravisBoatman** [comment]
Just an FYI, a new future version will no longer require a try/catch wrapper.

**Comment by TravisBoatman** [comment]
@AussieEevee commit ddc53bd has the changes I was referring to earlier, expect a new nuget package soon too.
