### ISSUE TITLE
Add Highmountain Tauren and Nightborne to Race.cs

### ISSUE THREAD

**Issue by TravisBoatman** [danjagnow/ArgentPonyWarcraftClient#48]
To find out the values for each race make a get request to https://us.api.battle.net/wow/data/character/races?locale=en_US&apikey=apiKey 
You'll need to register an api key first here https://dev.battle.net/member/register

**Comment by AussieEevee** [comment]
27 Nightborne
28 Highmountain
29 Void Elf
30 Lightforged

**Comment by TravisBoatman** [comment]
@AussieEevee I see you made a fork and made those changes. Did you want to create a pull request?
