### ISSUE TITLE
App freezes when trying to access statistics

### ISSUE THREAD

**Issue by AussieEevee** [danjagnow/ArgentPonyWarcraftClient#49]
Now, I will 100% admit that I am new to using lists in C#, so I apologise if my code is bad.

Right now I have 

long kills = x.Statistics.SubCategories[135].Statistics[107].Quantity;

The idea is to assign the total number of creature kills to the kills variable, but the API freezes the program when it gets here.

**Comment by TravisBoatman** [comment]
This isn't a problem with the API, but I can show you how to get the data you want. The data hierarchy that you get back from Blizzard is a bit unwieldy. Traversing through it is best done with LINQ. 

```csharp
var statistic = character.Value.Statistics.SubCategories
    .Where(x => x.Name == "Kills").FirstOrDefault()
    .SubCategories.Where(x => x.Name == "Creatures").FirstOrDefault()
    .Statistics.Where(x => x.Name == "Creatures killed").FirstOrDefault();

var kills = statistic.Quantity;
```

**Comment by AussieEevee** [comment]
That is awesome and works perfectly. Thank you.
