### ISSUE TITLE
Question: Why use a singleton?

### ISSUE THREAD

**Issue by willwolfram18** [danjagnow/ArgentPonyWarcraftClient#54]
What's the purpose of maintaining a singleton instance of the `HttpClient` with the `InternalHttpClient`? Is this a performance gain, or some other reason? Why not instead do the `HttpClient` initialization in the `WarcraftClient`'s constructor and have the class implement `IDisposable` and dispose of the client then?

**Comment by TravisBoatman** [comment]
Yes it's a performance increase and the proper way to use it. Here are some links explaining it better than I could. 

https://stackoverflow.com/a/22561368/5107677
https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by Bwolfing** [comment]
Shouldn't it be the responsibility of the consuming application to decide lifetime requirements though? While I get wanting to be efficient and use the `HttpClient` in an optimal manner, it's probably better to let the consumer decide how they want to make use of it. If an application is making infrequent use of an `HttpClient` they may not want it hanging around in memory between those requests.

**Comment by TravisBoatman** [comment]
Yeah that's a consideration I had before but never acted on it. We could definitely implement that by just adding an optional HttpClient parameter. However I think we should wait till the [new](https://github.com/aspnet/HttpClientFactory) HTTPClient is released.

**Comment by Bwolfing** [comment]
See my thought would be instead of requiring an `HttpClient` or the new factory, have the `WarcraftClient` effectively be an `HttpClient`; consumer's are expected to use it as a singleton for optimal performance, but if they don't that's on them. After all, this is effectively a wrapper around or extension of the `HttpClient` anyway.

**Comment by willwolfram18** [comment]
This is closed, at least in part, by #57 and the addition of the constructor which takes an `HttpClient`.
